version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./db:/var/lib/mysql'

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
